### ISSUE TITLE
Check out this post by {        map[]}

### ISSUE THREAD

**Issue by Libbum** [DrDJIng/DrDJIng.github.io#1]
Your 'email this post' subject line is misaligned it looks like.

**Comment by DrDJIng** [comment]
Pretty sure it has something to do with the weird interactions between "'s in this line:
<a href="mailto:?subject={{ i18n "check_out" }} {{ $author }}&amp;body={{ $permalink }}" <- " being carelessly thrown around and closing off things early.

But I couldn't get it to work, regardless of how I changed them, so I just changed it to call the title instead:
<a href="mailto:?subject= {{ $title }} &amp;body={{ $permalink }}" <- No extra " to be interfering.

This way I also get rid of the false hype, which I tend to find tacky.

Good find, thanks!
